# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeDashboard < Formula
  desc "k9s-style TUI for managing Claude Code sessions"
  homepage "https://github.com/seunggabi/claude-dashboard"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/seunggabi/claude-dashboard/releases/download/v0.9.1/claude-dashboard_0.9.1_darwin_amd64.tar.gz"
      sha256 "2979749f1d53db04d755358a0c5215e086392625a05bb7f03c1234177ce7a3fd"

      def install
        bin.install "claude-dashboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/seunggabi/claude-dashboard/releases/download/v0.9.1/claude-dashboard_0.9.1_darwin_arm64.tar.gz"
      sha256 "335b3d83fb2de22977ef373fdd3f8ccef1c22edf6985bf8580cb154c4c00b9ed"

      def install
        bin.install "claude-dashboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/seunggabi/claude-dashboard/releases/download/v0.9.1/claude-dashboard_0.9.1_linux_amd64.tar.gz"
      sha256 "9a6fff242334e0b1efe82819d7575e09c32754684b9261f6756547baa1b1804a"
      def install
        bin.install "claude-dashboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seunggabi/claude-dashboard/releases/download/v0.9.1/claude-dashboard_0.9.1_linux_arm64.tar.gz"
      sha256 "b196e124a1d9feab00bca7f6f7600b0b08496756382b51eb6966728427535f83"
      def install
        bin.install "claude-dashboard"
      end
    end
  end

  def post_install
    # Helper scripts are embedded in the binary
    # They will be installed automatically on first run
    system "#{bin}/claude-dashboard", "setup" rescue nil
  end

  def caveats
    <<~EOS
      Setup is automatic on first run, or run manually:
        claude-dashboard setup

      This will:
      - Install helper scripts to ~/.local/bin/
      - Configure ~/.tmux.conf for F12 mouse toggle
      - Add status bar with version info

      To start using claude-dashboard:
        claude-dashboard
    EOS
  end
end
