# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeDashboard < Formula
  desc "k9s-style TUI for managing Claude Code sessions"
  homepage "https://github.com/seunggabi/claude-dashboard"
  version "0.13.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/seunggabi/claude-dashboard/releases/download/v0.13.1/claude-dashboard_0.13.1_darwin_amd64.tar.gz"
      sha256 "5a3c6cfd942eaeefb4e0f0eac0a59672f055dba1f1a980113b2f9df533fd6d4c"

      define_method(:install) do
        bin.install "claude-dashboard"
        # Install helper scripts to a temporary location for setup to use
        libexec.install "scripts/tmux-mouse-toggle.sh"
        libexec.install "scripts/tmux-status-bar.sh"
        libexec.install "scripts/tmux-save-history.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/seunggabi/claude-dashboard/releases/download/v0.13.1/claude-dashboard_0.13.1_darwin_arm64.tar.gz"
      sha256 "0df7c433428253116f6ce798328c170333500131ffc880b85f205bee131e8d77"

      define_method(:install) do
        bin.install "claude-dashboard"
        # Install helper scripts to a temporary location for setup to use
        libexec.install "scripts/tmux-mouse-toggle.sh"
        libexec.install "scripts/tmux-status-bar.sh"
        libexec.install "scripts/tmux-save-history.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/seunggabi/claude-dashboard/releases/download/v0.13.1/claude-dashboard_0.13.1_linux_amd64.tar.gz"
      sha256 "9138eaaf6a7e31574717f74c86c561651f8ab5dc79bd20d2837a0eb3be9eee2e"
      define_method(:install) do
        bin.install "claude-dashboard"
        # Install helper scripts to a temporary location for setup to use
        libexec.install "scripts/tmux-mouse-toggle.sh"
        libexec.install "scripts/tmux-status-bar.sh"
        libexec.install "scripts/tmux-save-history.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seunggabi/claude-dashboard/releases/download/v0.13.1/claude-dashboard_0.13.1_linux_arm64.tar.gz"
      sha256 "222eddca5de457e2115b39ea1b29dc229cd0b4faeb309835b0b360eddce58569"
      define_method(:install) do
        bin.install "claude-dashboard"
        # Install helper scripts to a temporary location for setup to use
        libexec.install "scripts/tmux-mouse-toggle.sh"
        libexec.install "scripts/tmux-status-bar.sh"
        libexec.install "scripts/tmux-save-history.sh"
      end
    end
  end

  def post_install
    # Run setup to install scripts and configure tmux
    # Copy scripts from libexec to ~/.local/bin
    home = Dir.home
    local_bin = File.join(home, ".local", "bin")
    FileUtils.mkdir_p(local_bin)

    FileUtils.cp(File.join(libexec, "tmux-mouse-toggle.sh"), File.join(local_bin, "claude-dashboard-mouse-toggle"))
    FileUtils.cp(File.join(libexec, "tmux-status-bar.sh"), File.join(local_bin, "claude-dashboard-status-bar"))
    FileUtils.cp(File.join(libexec, "tmux-save-history.sh"), File.join(local_bin, "claude-dashboard-save-history"))
    FileUtils.chmod(0755, File.join(local_bin, "claude-dashboard-mouse-toggle"))
    FileUtils.chmod(0755, File.join(local_bin, "claude-dashboard-status-bar"))
    FileUtils.chmod(0755, File.join(local_bin, "claude-dashboard-save-history"))

    # Run setup to configure tmux
    system "#{bin}/claude-dashboard", "setup"
  end

  def caveats
    <<~EOS
      Setup was automatically run during installation.

      If you need to re-run setup:
        claude-dashboard setup

      This will:
      - Install helper scripts to ~/.local/bin/
      - Configure ~/.tmux.conf for F12 mouse toggle
      - Add status bar with version info

      To start using claude-dashboard:
        claude-dashboard
    EOS
  end
end
